version: '3.4'

services:
  orderapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  userapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  addressapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  productapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

